# Generated by Django 4.1.5 on 2023-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
