# Generated by Django 4.1.5 on 2023-03-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listingmodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingmodel',
            old_name='start_bid',
            new_name='bid',
        ),
    ]
