# Generated by Django 4.1.5 on 2023-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bid_listingmodel_start_bid_bidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watcher', to='auctions.listingmodel'),
        ),
    ]
