# Generated by Django 4.1.5 on 2023-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='category',
            field=models.CharField(default='Home', max_length=64),
            preserve_default=False,
        ),
    ]
