# Generated by Django 4.1.5 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listingmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
