# Generated by Django 4.1.5 on 2023-04-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listingmodel_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
