# Generated by Django 4.1.5 on 2023-05-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listingmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('listing', models.ManyToManyField(blank=True, related_name='category', to='auctions.listingmodel')),
            ],
        ),
    ]
