# Generated by Django 4.1.5 on 2023-05-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmodel',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listingmodel'),
        ),
        migrations.AlterField(
            model_name='bidmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='listing',
            field=models.ManyToManyField(blank=True, to='auctions.listingmodel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.listingmodel'),
        ),
    ]
