# Generated by Django 4.1.5 on 2023-05-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bidmodel_listing_alter_bidmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.categorymodel'),
        ),
    ]
